### ISSUE TITLE
Node.js: Compatibilidade de OS ao importar módulos.

### ISSUE THREAD

**Issue by lukaswilkeer** [Webschool-io/forum#10]
Vi um artigo semana passada (o qual não acho de jeito nenhum) falando que o windows interpreta os imports do node.js de forma diferente de sistemas *nix. 

Ex:
```
import { mongoose } from 'mongoose'
import { FileManager } from '../models/FileManager'
```
Neste artigo falava os imports deveriam ser feitos em `camelCase` para compatiblidade entre OS. 

Alguém pode me indicar algum _artigo/qualquer coisa_ sobre isso?

**Comment by rafaelvicio** [comment]
Para módulos exportados com NPM o nome e padrão.
Para módulos que você criou eu acho que só vai depender do nome que você deu a eles. 

Desconheço esse problema de compatibilidade entre OS.

Estou procurando artigos mas não encontrei nenhum relacionado.

**Comment by lukaswilkeer** [comment]
Achei o que tinha visto, foi na documentação do Heroku sobre Node.js 
A indicação é para a nomeclatura dos arquivos.

> Stick with lowercase
Some languages encourage filenames that match class names, like MyClass and 'MyClass.js’. Don’t do that in node. Instead, use lowercase files:

> `let MyClass = require('my-class');`

>Node.js is the rare example of a Linux-centric tool with great cross-platform support. **While OSX and Windows will treat 'myclass.js’ and 'MyClass.js’ equivalently, Linux won’t.** To write code that’s portable between platforms, you’ll need to exactly match require statements, including capitalization.
The easy way to get this right is to just stick with lowercase filenames for everything, eg 'my-class.js’.

https://devcenter.heroku.com/articles/node-best-practices#stick-with-lowercase
