### ISSUE TITLE
Recuperando dados do usuario logado

### ISSUE THREAD

**Issue by rafaelvicio** [Webschool-io/forum#11]
Pessoal, estou com uma duvida que acredito que seja muito boba.

Implementei uma autenticação utilizando estrategia do Github.

passport:
`var passport = require('passport');
var GitHubStrategy = require('passport-github').Strategy;
var mongoose = require('mongoose');

module.exports = function() {
	
	var Usuario = mongoose.model('Usuario');

	passport.use(new GitHubStrategy({
		clientID: 'fd1b4c7fbf9173c1faf7',
		clientSecret: '3588af70ba74ce583757c336a49da034d47442ed',
		callbackURL: 'http://localhost:3000/auth/github/callback'
	}, function(accessToken, refreshToken, profile, done) {
		
		Usuario.findOrCreate(
			{ "login" : profile.username}, 
			{ "nome" : profile.username},  
			function(erro, usuario) {
				if(erro) {
					return done(erro);
				} 
				return done(null, usuario);
			}
		);
	}));

	passport.serializeUser(function(usuario, done) {
	  done(null, usuario._id);
	});

	passport.deserializeUser(function(id, done) {
	  Usuario.findById(id).exec()
	  .then(function(usuario) {
	  	done(null, usuario);	
	  });
	});
};`

route auth:
`var passport = require('passport');

module.exports = function(app){

  app.get('/auth/github', 
        passport.authenticate('github'));
    app.get('/auth/github/callback',
        passport.authenticate('github', {
        failureRedirect: '/'}),
        function (req, res) {
            
        //sucesso na autenticação
        res.redirect('/#!/painel/index');
    });

};`

Eu verifico se o usuario esta autenticado nas minhas rotas:
`function verificaAutenticacao(req, res, next) {
  if (req.isAuthenticated()) {
    return next();
  } else {
    res.status('401').json('Não autorizado');
  }
}

module.exports = function(app){

  var api = app.api.time;

  app.route('/api/times')
    .get(verificaAutenticacao, api.lista)
    .post(verificaAutenticacao, api.adiciona);

  app.route('/api/times/:id')
      .get(verificaAutenticacao, api.buscaPorId)
      .delete(verificaAutenticacao, api.removePorId)
      .put(verificaAutenticacao, api.atualiza);

};`

no angularJS eu tenho um interceptador:
`angular.module('alurapic')
    .factory('meuInterceptor', function($q, $location) {

    var meuInterceptor = {
    	responseError: function(resposta) {
    		if (resposta.status == 401) {
    		  $location.path('/auth');
    		}
            return $q.reject(resposta);
    	}
    }

        return meuInterceptor;
    });`

Blz, esta tudo funcionando na autenticação.
Agora eu quero recuperar os dados do usuario que esta autenticado e exibir em uma pagina do AngularJS, como eu poderia fazer isso?

Preciso de um serviço? E chamar ele no controller?

**Comment by suissa** [comment]
Primeiro: pq usar o `findOrCreate `??

Se vc estiver fazendo o login deve usar apenas o `findOne`, se for cadastrar use o `create` e se for alterar o `update`.

Sobre interceptors veja essa aula https://www.youtube.com/watch?v=I89E75mUmbc

**Comment by rafaelvicio** [comment]
@suissa Se eu ja tiver cadastro uma conta pelo formulario normal, e depois quiser logar com o acesso ao GitHub. Se eu utilizar o Create não daria problema?

**Comment by suissa** [comment]
@rafaelvicio Uai mas se vc ja usa findOrCreate e fora q se ele quiser logar com o Github ai eh um update e não create

**Comment by rafaelvicio** [comment]
Eu vou melhorar essa parte do código, mas queria voltar ao assunto do issue.
Como vo pegar o nome do usuário que esta logado no momento?

**Comment by lukaswilkeer** [comment]
@rafaelvicio 

Quando você logar o user você registra uma session no back-end.
Ref: [Express-session](https://expressjs.com/en/resources/middleware/session.html)

Quando você registra uma sessão, irá retornar o ID, o qual você pode gravar no cookie, por exemplo. Porém você pode gravar em vários locais e até mesmo no banco de dados.

Quando você precisar das info do user logado, você chama uma API, ex, `GET /auth/session/:session_id` (o nome foi só pra saber o que a rota faz), a qual retorna as informações do usuário logado para o Angular.
