### ISSUE TITLE
Estágio em desenvolvimento web full-stack.

### ISSUE THREAD

**Issue by henriquechaves** [Webschool-io/forum#12]
Venha fazer parte do MqLab!

Nós somos um laboratório de Inovação dentro da Mastermaq Software. Estamos procurando por uma ou um estudante para vaga de estágio em desenvolvimento web full-stack.

Você está cursando ciência da computação, engenharia de software, sistema de informação, design, produção multimídia ou algum outro curso semelhante? Você entende o básico de HTML, CSS, JavaScript? Está com previsão de formatura para daqui 1 ano ou mais?

Se sim, essa vaga é pra você!

Aqui você vai aprender muito e se desenvolver profissionalmente!

Ficou interessado? Acesse o link e preencha o formulário! goo.gl/21dNTF

https://www.facebook.com/mastermaq.software/photos/a.429770843708835.105210.416504851702101/1691668637519043/?type=3&theater

**Comment by ghost** [comment]
a vaga é de qual cidade?

**Comment by suissa** [comment]
@mcarvalho BOA PERGUNTA até entrei no form deles e não achei https://docs.google.com/forms/d/e/1FAIpQLSf5tM-uNzWo2uxIOR6N1QG26uWB0qCCCJFLAFDfxZY4e3SzUQ/viewform

**Comment by henriquechaves** [comment]
A vaga é para Belo Horizonte

**Comment by FabaoAnalista** [comment]
Irado em galera , seguinte estou para iniciar um estágio aqui mesmo onde faço facul , mas esta oportunidade é realmente diferenciada, vou me inscrever.

**Comment by lukaswilkeer** [comment]
@henriquechaves formação acadêmica é um requisito que pode dispensar o candidato?

**Comment by suissa** [comment]
Acredito que a maioria dos estágios sejam destinados aos alunos iniciantes que estão na Faculdade, o que eu acho uma besteira.

**Comment by lukaswilkeer** [comment]
Na dúvida, me inscrevi assim mesmo.
Antes pedir desculpas do que permissão (dependendo do caso).

**Comment by houstondapaz** [comment]
Acho que a treta é que o contrato de estágio precisa ter uma instituição de ensino assinando junto, por isso a exigência.
Mas eu só acho

**Comment by henriquechaves** [comment]
Olá pessoal, 

A formação acadêmica não é um pré-requisito, porém a contratação de estagiários está sujeita 
a algumas normas estabelecidas pelo MEC.  Por este motivo ao descrevermos a vaga colocamos que os candidatos devem estar cursando ciência da computação, engenharia de software, sistema de informação, design, produção multimídia ou algum outro curso semelhante.

Essa é uma rigidez inescapável nos programas de estágio que não se aplica necessariamente aos cargos efetivos de desenvolvimento.

Abraço

**Comment by FabaoAnalista** [comment]
Boa noite,

Isso é até uma obviedade visto que o estágio é regulamentado por lei e prêve a obrigatoriedade do estagiando a uma instituição de ensino .

**Comment by lukaswilkeer** [comment]
Boa noite,

Eu segui o raciocínio:

1. Provavelmente os cadastros vão para uma base de currículo.
2. Provavelmente irão analisar meu perfil.
3. E talvez, mesmo que pequena a possibilidade, podem se interessar pelo meu perfil e me chamar para uma entrevista, seja para algum estágio (tendo que me inscrever em alguma instituição) ou vaga como Dev. Jr (caso tenha).

As vezes, arriscar vale mais do que ficar parado por uma 'obviedade'.
Se houver vaga para `dev`, em qualquer lugar, saibam que estou disponível. 

Abraços a todos.

**Comment by suissa** [comment]
@lukaswilkeer Se chamarem vc EU GARANTO q teu JS estará tinindoooo!
