### ISSUE TITLE
Erro: DeprecationWarning: Mongoose: mpromise

### ISSUE THREAD

**Issue by rafaelvicio** [Webschool-io/forum#13]
Estou recebendo o seguinte erro ao iniciar a minha API Node(Express) com MongoDB.

> (node:15400) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html

Meu código esta da seguinte forma:

```
var mongoose = require('mongoose');
var api = {};

var model = mongoose.model('Usuario');

api.adiciona = function(req, res) {

  model
    .create(req.body)
      .then(function(){
        res.json(usuario);

      }, function(error) {
        console.log(error);
        res.status(500).json(error);
      });

};

api.atualiza = function(req, res) {

  model
    .findByIdAndUpdate(req.params.id, req.body)
      .then(function(usuario) {
        res.json(usuario);

      }, function(error) {
        console.log(error);
        res.status(500).json(error);
      });

};

api.lista = function(req, res) {

  model
    .find({})
    .then(function(usuarios) {
      res.json(usuarios);

    }, function(error) {
      console.log(error);
      res.status(500).json(error);
    });

};

api.buscaPorId = function(req, res) {

  model
    .findById(req.params.id)
      .then(function(usuario){
        if(!usuario) throw Error('usuario não encontrada');
        res.json(usuario);

      }, function(error){
        console.log(error);
        res.status(500).json(error);
      });

};

api.removePorId = function(req, res) {

  model
    .remove({_id: req.params.id})
      .then(function(){
        res.sendStatus(204);
      }, function(error) {
        console.log(error);
        res.status(500).json(error);
      });

};

module.exports = api;
```

**Comment by lukaswilkeer** [comment]
O Mongoose não tem mais a lib de promesas próprias, é necessário você plugar alguma, que pode ser a que você quiser, inclusve a built-in do JS.
[Neste artigo](https://spion.github.io/posts/why-i-am-switching-to-promises.html), (bem foda) tem uma comparação de várias libs. Vou seguir com o exemplo da bluebird.

Ex:
```javascript
const mongoose = require('mongoose')
const bluebird = require('bluebird')
mongoose.Promise = bluebirdd`
//Configurações da lib (opcional)
bluebird.config({
    // Enable warnings
    warnings: true,
    // Enable long stack traces
    longStackTraces: true,
    // Enable cancellation
    cancellation: true,
    // Enable monitoring
    monitoring: true
})
```
Na declaração do `Schema` você "promisifica" ele.

```javascript
const User = db.model('User', authSchema);
bluebird.promisifyAll(User)
bluebird.promisifyAll(User.prototype);
```
E pá! Mágica acontece.

Não é necessário o `bluebird.config()`, mas ajuda muito a debugar durante o desenvolvimento. 
Somente a lib `Q` que tem uma diferença na hora de fazer o require, porém está na doc do `mongoose`.

**Documentação:**
- [Documentação mongoose promises](http://mongoosejs.com/docs/promises.html)
- [Documentação das configurações da bluebird](http://bluebirdjs.com/docs/api/promise.config.html)

**Comment by suissa** [comment]
@lukaswilkeer eu uso global.Promise já q o Node já possui Promises nativas, dessa forma não necessitando de mais uma lib para tal.

**Comment by rafaelvicio** [comment]
Eu tive que mudar para o seguinte:

`  mongoose.connect('mongodb://' + uri, {
    useMongoClient: true
  });

  mongoose.Promise = global.Promise`

Funcionou ;)

**Comment by suissa** [comment]
@rafaelvicio manooo vc está usando errado as Promises, SEMPRE use com then e catch

**Comment by rafaelvicio** [comment]
@suissa assim:?

```
api.adiciona = function(req, res) {

  model
    .create(req.body)
      .then(function(){
        res.json(usuario);

      })
      
      .catch(function(error) {
        console.log(error);
        res.status(500).json(error);
      })
};
```

**Comment by suissa** [comment]
@rafaelvicio Quase, eu faria assim:

```js
const sendError = ( res ) => ( error ) => {
  console.log( error )
  return res.status( 500 ).json( error )
} 
  // arrumei soh esse
const adiciona = ( req, res ) => 
  model.create( req.body )
        .then( ( usuario ) => res.json( usuario ) )
        .catch( sendError( res ) )
```
