### ISSUE TITLE
Guardar informações do ususario autenticado

### ISSUE THREAD

**Issue by rafaelvicio** [Webschool-io/forum#16]
Estou com minha autenticação via token funcionando normalmente na minha aplicação feita em NodeJS(Express) e AngularJS.

Mas agora eu queria retirar informações do ususario que esta autenticado para fazer algumas coisas. Qual seria a melhorar estrategia para fazer isso? Ja dei uma lida e estou com algumas opções como retirar a informações do payload do token, ao logar, salvar o nome ou id do ususario no sesson storage.

Queria a opinição de voces, qual seria a melhor forma? exemplos?

**Comment by vinicius73** [comment]
Geralmente eu crio uma rota que me informa todos os dados do usuário 
Uso junto com o bootstrap da aplicação, assim tbm garanto que o token é válido 

Uma vez que faço esse processo libero a aplicação para o usuário. 

Essa informação não vai pro storage, e sim para algum objeto que eu possa recuperar com facilidade. 

No vue coloco no vuex.

**Comment by rafaelvicio** [comment]
Mas como voce consegue essas informações que voce guarda no objeto? Quando o usuário realiza o login ou atraves do token depois?

Eu não conheço o vuex, aonde voce guarda e como voce recupera?

**Comment by vinicius73** [comment]
- ao carregar a pagina (f5) tem token? recupero os dados
- ao carregar a pagina (f5) não tem token? vá formulário de login
- login com sucesso? recupero os dados

normalmente uso uma rota `GET /me` ou `GET /auth/me`

Vuex é uma "fonte única da verdade" [(single source of truth)](https://en.wikipedia.org/wiki/Single_source_of_truth)

mais informações aqui: https://blog.codecasts.com.br/estados-com-vue-js-data-computed-props-e-store-d8c6da4627ca

**Comment by rafaelvicio** [comment]
Obrigado @vinicius73 

Consegui fazer isso no interceptor!

```
angular.module('alurapic')
    .factory('tokenInterceptor', function($q, $window, $location) {

        var interceptor = {};

        interceptor.response = function (response) {
            var token = response.headers('x-access-token');
            if (token) {
                $window.localStorage.token = token;
            }
            return response;
        },

        interceptor.request = function (config) {
            config.headers = config.headers || {};

            if ($window.localStorage.token) {
                config.headers['x-access-token'] = $window.localStorage.token;
            }

            return config;
        },

        interceptor.responseError = function(rejection) {

            if (rejection != null && rejection.status === 401) {
                console.log('Removendo token da sessão')
                delete $window.sessionStorage.token;
                $location.path("/login");
            } 
            return $q.reject(rejection);
        }

    return interceptor;

});
```
