### ISSUE TITLE
Entendendo os parâmetros das funções no JavaScript

### ISSUE THREAD

**Issue by rafaelvicio** [Webschool-io/forum#3]
Estou com uma duvida em relação a como o JavaScript entende os parâmetros passados na função do JavaScript. 

```
var alunos = [
    {nome: 'Rafael', idade: 20},
    {nome: 'Filype', idade: 17},
    {nome: 'Maria', idade: 18}
]
var alunosDeMaior = alunos.filter(function(aluno) {
    return aluno.idade >= 18;
})
console.log(alunosDeMaior);
```

Aqui eu passo para a função de callback do filter uma função que recebe um 'aluno' e verifica se o aluno tem idade maior que 18. Porem, como ele sabe o que é um aluno?

Eu posso trocar para:

var alunosDeMaior = alunos.filter(function(a) {
    return a.idade >= 18;
})

É o código continua funcionando corretamente. Se passar eu passar por exemplo 2 parâmetros para essa função, posso ter problemas? Como isso funciona?

**Comment by suissa** [comment]
Analise comigo o que diz a documentação do filter:

```
Parâmetros

callback
Função é um predicado, para testar cada elemento do array. Returna true para manter o elemento, false caso contrário, recebendo três argumentos:

element
O elemento que está sendo processado no array.

index
O índice do elemento atual que está sendo processado no array.

array
O  filter do array foi chamado.

```

fonte: [https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Global_Objects/Array/filtro](https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Global_Objects/Array/filtro)

Então ele sempre recebe uma função com esses 3 parâmetros, no caso quando vc passa só um vc está pegando apenas o `element` que no caso pode ser qualquer coisa e é sua função que precisa indicar sua estrutura.

**Comment by rafaelvicio** [comment]
Perfeito @suissa!
