### ISSUE TITLE
'Let' matou o 'var' de vez?

### ISSUE THREAD

**Issue by rafaelvicio** [Webschool-io/forum#4]
Os conceitos de CONST e LET que foram adicionados no ES6 ja estão bem claros na minha mente. Mas ainda existe alguma situação em que o uso de VAR ainda e necessário?

**Comment by anabastos** [comment]
`var` ainda pode ser usado caso voce queira uma variável com escopo de função mas eu pessoalmente não acho que faz sentido usar se seu codigo esta na ES6.

**Comment by rafaelvicio** [comment]
Pra escopo de função eu poderia usar o `let` mesmo, não? Acho que a unica diferença mesmo vai ser se eu precisar de algo que o “hoisting” do `let` não posso atender.

**Comment by lukaswilkeer** [comment]
Minha visão sobre o assunto: 
Pode usar `var`? Pode. É necessário? Não.

Usando `let` no lugar de `var` você vai ter a certeza do escopo dela. Isso é um ponto a favor. Usar `const` junto com `let` é mais semântico (pra mim) do que `const` e `var`.

**Comment by suissa** [comment]
@anabastos Não faz nenhum sentido usar var hoje em dia.

**Comment by rafaelvicio** [comment]
Então ja era, o negocio e 'const' e 'let'. haha

**Comment by suissa** [comment]
@rafaelvicio uso let apenas para contadores

**Comment by giuseppeM99** [comment]
@rafaelvicio rip

**Comment by suissa** [comment]
`var` só serve para fazer hoisting!
