### ISSUE TITLE
Bloquear rotas do AnguarJS 

### ISSUE THREAD

**Issue by rafaelvicio** [Webschool-io/forum#6]
Eu estou utilizando 'passport' e 'passport-github' no meu back-end em NodeJS. Consigo restringir as rotas da API de forma tranquila. 

Estou com duvida na parte do AngularJS, até o momento eu fiz apenas o meu interceptor para verificar se o retorno foi 401.

```
angular.module('alurapic')
    .factory('meuInterceptor', function($q, $location) {

    var meuInterceptor = {
    	responseError: function(resposta) {
    		if (resposta.status == 401) {
    		  $location.path('/auth');
    		}
            return $q.reject(resposta);
    	}
    }

        return meuInterceptor;
    });
```

Mas como eu poderia bloquear uma rota por exemplo /painel/ para que so possa acessar quem esta autorizado pelo passport?

O código do meu back-end esta disponível em: [GitHub](https://github.com/rafaelvicio/github-autenticacao-exemplo)

**Comment by kurybr** [comment]
https://github.com/angular-ui/ui-router/wiki
Esse link pode te ajudar mano.
Mas colocando no Routes, um atributo vendo se é uma rota autenticada, ajuda já. 
```javascript
{
	url: '/home',
	auth: true,
	params: {
		user: null
	}
	, views: {
		'@': {
			templateUrl: 'templates/onboarding/home.html',
			controller: 'controller-onboarding-home as vm'
		}
	}
}


// -----------

$rootScope.$on('$stateChangeSuccess', ChangeStateConfig);

function ChangeStateConfig(event, toState, toParams, from, fromParams) {
	if (toState.auth) {	
	/// verifica se está autenticado, e se não tiver pausa e sai.
	        event.preventDefault();
		$state.go('....')
	}
}
```

**Comment by suissa** [comment]
@kurybr Meinnn eh soh vc usar o resolve na rota e chamar uma função no Controller q teste o user e caso nao esteja autenticado vc manda um redirect. PAPUM

**Comment by rafaelvicio** [comment]
@suissa Isso pode virar um serviço, certo?
@kurybr Eu tinha visto esse tipo de implementação em alguns artigos, vou tentar implementar ele.

Obrigado!
