### ISSUE TITLE
Funcionalidades de uma API Rest

### ISSUE THREAD

**Issue by rafaelvicio** [Webschool-io/forum#8]
Pessoal, quais são as funcionalidades que voces consideram como basicas de uma API estilo REST?

**Comment by suissa** [comment]
@rafaelvicio CRUD, paginação, token é o que pensei assim de primeira.

**Comment by lubien** [comment]
Auth e qualquer coisa q vc poderia fazer no site (supondk q ele tenha uma versao nao-spa) possa ser feita com ela tbm

**Comment by rafaelvicio** [comment]
@suissa Tem algum exemplo de paginação para API?

**Comment by malaquiasdev** [comment]
http://pokeapi.co/docsv2/

Um bom exemplo de API REST, mesmo eu não gostando da modelagem dos JSON deles.

Eles fazem paginação pra não te retornar todos 844 pokémons de uma vez também

**Comment by lukaswilkeer** [comment]
@rafaelvicio Retornar em JSON. Quando vejo algo que não retorna JSON meu coração até dói.

**Comment by rafaelvicio** [comment]
@lukaswilkeer JSON sempre, qualquer coisa fora disso esta fora de discussão. Minhas duvidas estão mais voltadas as features de uma API Rest mesmo. 

Mas acho que minha duvida já foi respondida:

- Autenticação
- Paginação
